import {cp,mkdir} from 'node:fs/promises';
import {build} from 'esbuild';
await mkdir('dist/public',{recursive:true});
await mkdir('dist/database',{recursive:true});
await cp('apps/school-web/public','dist',{recursive:true});
await cp('apps/school-web/public','dist/public',{recursive:true});
for (const outfile of ['dist/app.js','dist/public/app.js']) await build({entryPoints:['apps/school-web/public/app.js'],bundle:true,format:'esm',platform:'browser',target:'es2022',outfile,minify:true});
await cp('apps/school-web/server.mjs','dist/server.mjs');
await cp('apps/school-web/database.mjs','dist/database.mjs');
await cp('apps/school-web/auth-server.mjs','dist/auth-server.mjs');
await cp('apps/school-web/mailer.mjs','dist/mailer.mjs');
await cp('apps/school-web/database/schema.sql','dist/database/schema.sql');
console.log('School portal frontend and Node.js server built in dist.');
